# Generated by Django 6.1.1 on 2026-09-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_users_db_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_db',
            name='user',
        ),
        migrations.AddField(
            model_name='users_db',
            name='password',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_db',
            name='username',
            field=models.CharField(default='adminn', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
